[[redirects]]
  from = "/login"
  to = "/login"
  status = 200
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/productList"
  to = "/productList"
  status = 200
  force = true # COMMENT: ensure that we always redirect

